version: "3.8"
services:
  frontend:
    environment:
      - API_URL=http://backend:5000
    build: ./frontend
    ports: 
      - 3000:3000

  backend:
    build: ./backend
    ports: 
      - 5000:5000
