CREATE TABLE IF NOT EXISTS foxes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	content TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id)
    REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  password TEXT NOT NULL,
  UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS tokens (
  user_id INTEGER PRIMARY KEY NOT NULL,
  token TEXT UNIQUE NOT NULL,
  FOREIGN KEY (user_id)
    REFERENCES users(id)
);