CREATE TABLE IF NOT EXISTS foxes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	content TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user (
  user_id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS token (
  token_id INTEGER PRIMARY KEY AUTOINCREMENT,
  token TEXT NOT NULL,
  FOREIGN KEY (token_id),
    REFERENCES user(user_id)
);